"""Create Faq_User

Revision ID: 3a8f02636160
Revises: 
Create Date: 2026-07-31 22:30:46.822797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8f02636160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Faq_User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ask', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Faq_User')
    # ### end Alembic commands ###
